using RobotGryphon.Modifi.Domains;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RobotGryphon.Modifi.Packs {
    public struct Pack {

        public string Name;

        /// <summary>
        /// The currently-installed version.
        /// This is generated by encrypting it with <see cref="ModifiVersion.ToHash">ModifiVersion</see>.
        /// </summary>
        public string Installed;

        // TODO
        public Dictionary<String, Domain> Domains;

        public string MinecraftVersion;
    }
}
