using System;
using System.Collections.Generic;
using Modifi.Domains;
using Newtonsoft.Json;

namespace Modifi.Packs {
    public class Pack : IDisposable {

        public string Name;

        /// <summary>
        /// The currently-installed version.
        /// This is generated by encrypting it with <see cref="ModifiVersionNumber.ToHash">ModifiVersion</see>.
        /// </summary>
        public string Installed;

        [JsonIgnore]
        public Dictionary<string, IDomain> Domains;
        
        public IEnumerable<string> UseDomains { get; set; }

        public string MinecraftVersion;

        public Pack() {
            this.Domains = new Dictionary<string, IDomain>();
            this.UseDomains = new List<string>();            
        }

        public void Dispose() {
            // Do nothing here unless necessary, it's to make code look a bit nicer if people wanna do using()
        }

        public IDomain GetDomain(string id) {
            if (Domains.ContainsKey(id)) return Domains[id];
            try {

                ConsoleColor old = Console.ForegroundColor;
                Console.ForegroundColor = ConsoleColor.Gray;
                Modifi.DefaultLogger.Information("Domain {0:l} not loaded, loading it now.", id);
                Console.ForegroundColor = old;

                IDomain domain = DomainHelper.LoadDomain(this, id);
                return domain;
            }

            catch(Exception e) {
                Modifi.DefaultLogger.Error(e.Message);
                return null;
            }
        }

        public IEnumerable<IDomain> GetRequiredDomains() {
            return Domains.Values;
        }
    }
}
